(function () {
   window.localizedStrings = {
      'ar-sa':
      {
         Jan: '$2 يناير',
         Feb: '$2 فبراير',
         Mar: '$2 مارس',
         Apr: '$2 أبريل',
         May: '$2 مايو',
         Jun: '$2 يونيو',
         Jul: '$2 يوليو',
         Aug: '$2 أغسطس',
         Sep: '$2 سبتمبر',
         Oct: '$2 أكتوبر',
         Nov: '$2 نوفمبر',
         Dec: '$2 ديسمبر',
         'Books & Reference': 'الكتب + المراجع',
         Business: 'الأعمال',
         'Developer Tools': 'أدوات المطوّر',
         Education: 'التعليم',
         Entertainment: 'الترفيه',
         'Government & Politics': 'الحكومة + السياسة',
         'Health & Fitness': 'الصحة + اللياقة',
         'Kids & Family': 'العائلة + الأطفال',
         Lifestyle: 'أسلوب الحياة',
         'Food & Dining': 'الطعام + المطاعم',
         'Multimedia Design': 'تصميم الوسائط المتعددة',
         Medical: 'طبي',
         Music: 'الموسيقى',
         'Navigation & Maps': 'التنقل + الخرائط',
         'News & Weather': 'الأخبار + الطقس',
         'Personal Finance': 'التمويل الشخصي',
         'Photo & video': 'الصور + الفيديو',
         Productivity: 'الإنتاجية',
         Security: 'الأمان',
         Shopping: 'التسوق',
         Social: 'التواصل الاجتماعي',
         Sports: 'الرياضة',
         Travel: 'السفر',
         'Utilities & tools': 'الأدوات المساعدة + الأدوات',
         Games: 'الألعاب',
         Personalization: 'التخصيص',
         Other: 'غير ذلك',
         IAP: 'الشراء داخل التطبيقات',
         'Paid Apps': 'التطبيقات المدفوعة',
         'APAC': 'آسيا المطلة على المحيط الهادئ',
         'Canada': 'كندا',
         'Central and Eastern Europe': 'وسط وشرق أوروبا',
         'France': 'فرنسا',
         'Germany': 'ألمانيا',
         'Greater China': 'الصين العظمى',
         'India': 'الهند',
         'Japan': 'اليابان',
         'Latam': 'أمريكا اللاتينية',
         'MEA': 'الشرق الأوسط وإفريقيا',
         'UK': 'المملكة المتحدة',
         'United States': 'الولايات المتحدة',
         'Western Europe': 'غرب أوروبا',
         'World': 'العالم'
      },
      'cs-cz':
      {
         Jan: 'Led $2',
         Feb: 'Úno $2',
         Mar: 'Bře $2',
         Apr: 'Dub $2',
         May: 'Kvě $2',
         Jun: 'Čvn $2',
         Jul: 'Čvc $2',
         Aug: 'Srp $2',
         Sep: '$2',
         Oct: 'Říj $2',
         Nov: 'Lis $2',
         Dec: 'Pro $2',
         'Books & Reference': 'Knihy + příručky',
         Business: 'Byznys',
         'Developer Tools': 'Vývojářské nástroje',
         Education: 'Vzdělávání',
         Entertainment: 'Zábava',
         'Government & Politics': 'Státní správa + politika',
         'Health & Fitness': 'Zdraví + fitness',
         'Kids & Family': 'Děti a rodina',
         Lifestyle: 'Životní styl',
         'Food & Dining': 'Jídlo + stravování',
         'Multimedia Design': 'Multimediální tvorba',
         Medical: 'Lékařství',
         Music: 'Hudba',
         'Navigation & Maps': 'Navigace + mapy',
         'News & Weather': 'Zprávy + počasí',
         'Personal Finance': 'Osobní finance',
         'Photo & video': 'Fotky + videa',
         Productivity: 'Produktivita',
         Security: 'Zabezpečení',
         Shopping: 'Nakupování',
         Social: 'Sociální sítě',
         Sports: 'Sport',
         Travel: 'Cestování',
         'Utilities & tools': 'Pomůcky + nástroje',
         Games: 'Hry',
         Personalization: 'Přizpůsobení',
         IAP: 'Nákup z aplikace',
         Other: 'Ostatní',
         'Paid Apps': 'Placené aplikace',
         'APAC': 'Asie a Tichomoří',
         'Canada': 'Kanada',
         'Central and Eastern Europe': 'Střední a východní Evropa',
         'France': 'Francie',
         'Germany': 'Německo',
         'Greater China': 'Velká Čína',
         'India': 'Indie',
         'Japan': 'Japonsko',
         'Latam': 'Latinská Amerika',
         'MEA': 'Střední východ, Afrika',
         'UK': 'Velká Británie',
         'United States': 'Spojené státy',
         'Western Europe': 'Západní Evropa',
         'World': 'Svět'
      },
      'da-dk':
      {
         Jan: 'Jan $2',
         Feb: 'Feb $2',
         Mar: 'Mar $2',
         Apr: 'Apr $2',
         May: 'Maj $2',
         Jun: 'Jun $2',
         Jul: 'Jul $2',
         Aug: 'Aug $2',
         Sep: 'Sep $2',
         Oct: 'Okt $2',
         Nov: 'Nov $2',
         Dec: 'Dec $2',
         'Books & Reference': 'Bøger og reference',
         Business: 'Erhverv',
         'Developer Tools': 'Udviklerværktøjer',
         Education: 'Uddannelse',
         Entertainment: 'Underholdning',
         'Government & Politics': 'Det offentlige og politik',
         'Health & Fitness': 'Sundhed og fitness',
         'Kids & Family': 'Børn og familie',
         Lifestyle: 'Livsstil',
         'Food & Dining': 'Mad og drikke',
         'Multimedia Design': 'Multimediedesign',
         Medical: 'Medicinsk',
         Music: 'Musik',
         'Navigation & Maps': 'Navigation og kort',
         'News & Weather': 'Nyheder og vejr',
         'Personal Finance': 'Personlig økonomi',
         'Photo & video': 'Billeder og video',
         Productivity: 'Produktivitet',
         Security: 'Sikkerhed',
         Shopping: 'Shopping',
         Social: 'Sociale værktøjer',
         Sports: 'Sport',
         Travel: 'Rejser',
         'Utilities & tools': 'Hjælpeprogrammer og værktøjer',
         Games: 'Spil',
         Personalization: 'Personlig tilpasning',
         Other: 'Andet',
         IAP: 'Produkt i app',
         'Paid Apps': 'Betalte apps',
         'APAC': 'APAC',
         'Canada': 'Canada',
         'Central and Eastern Europe': 'Central- og Østeuropa',
         'France': 'Frankrig',
         'Germany': 'Tyskland',
         'Greater China': 'Storkina',
         'India': 'Indien',
         'Japan': 'Japan',
         'Latam': 'Latinamerika',
         'MEA': 'MEA',
         'UK': 'Storbritannien',
         'United States': 'USA',
         'Western Europe': 'Vesteuropa',
         'World': 'Verden'
      },
      'de-de':
      {
         Jan: 'Jan. $2',
         Feb: 'Feb. $2',
         Mar: 'März $2',
         Apr: 'Apr. $2',
         May: 'Mai $2',
         Jun: 'Juni $2',
         Jul: 'Juli $2',
         Aug: 'Aug. $2',
         Sep: 'Sept. $2',
         Oct: 'Okt. $2',
         Nov: 'Nov. $2',
         Dec: 'Dez. $2',
         'Books & Reference': 'Bücher + Lexika',
         Business: 'Unternehmen',
         'Developer Tools': 'Entwicklungstools',
         Education: 'Bildung',
         Entertainment: 'Unterhaltung',
         'Government & Politics': 'Behörden + Politik',
         'Health & Fitness': 'Gesundheit + Fitness',
         'Kids & Family': 'Kinder und Familie',
         Lifestyle: 'Lifestyle',
         'Food & Dining': 'Essen + Trinken',
         'Multimedia Design': 'Multimediadesign',
         Medical: 'Medizin',
         Music: 'Musik',
         'Navigation & Maps': 'Navigation + Karten',
         'News & Weather': 'News + Wetter',
         'Personal Finance': 'Meine Finanzen',
         'Photo & video': 'Fotos + Videos',
         Productivity: 'Produktivität',
         Security: 'Sicherheit',
         Shopping: 'Shopping',
         Social: 'Soziale Netzwerke',
         Sports: 'Sport',
         Travel: 'Reise',
         'Utilities & tools': 'Dienstprogramme + Tools',
         Games: 'Spiele',
         Personalization: 'Personalisierung',
         Other: 'Sonstige',
         IAP: 'IAP',
         'Paid Apps': 'Kostenpflichtige Apps',
         'APAC': 'APAC',
         'Canada': 'Kanada',
         'Central and Eastern Europe': 'Mittel- und Osteuropa',
         'France': 'Frankreich',
         'Germany': 'Deutschland',
         'Greater China': 'Großchina',
         'India': 'Indien',
         'Japan': 'Japan',
         'Latam': 'Lateinamerika',
         'MEA': 'Naher Osten und Afrika',
         'UK': 'Vereinigtes Königreich',
         'United States': 'Vereinigte Staaten',
         'Western Europe': 'Westeuropa',
         'World': 'Welt'
      },
      'el-gr':
      {
         Jan: 'Ιαν. $2',
         Feb: 'Φεβ. $2',
         Mar: 'Μάρ. $2',
         Apr: 'Απρ. $2',
         May: 'Μάιος $2',
         Jun: 'Ιούν. $2',
         Jul: 'Ιούλ. $2',
         Aug: 'Αύγ. $2',
         Sep: 'Σεπ. $2',
         Oct: 'Οκτ. $2',
         Nov: 'Νοέμ. $2',
         Dec: 'Δεκ. $2',
         'Books & Reference': 'Βιβλία + αναφορά',
         Business: 'Επιχειρήσεις',
         'Developer Tools': 'Εργαλεία προγραμματισμού',
         Education: 'Εκπαίδευση',
         Entertainment: 'Ψυχαγωγία',
         'Government & Politics': 'Δημόσια διοίκηση',
         'Health & Fitness': 'Υγεία + ευεξία',
         'Kids & Family': 'Παιδιά + οικογένεια',
         Lifestyle: 'Lifestyle',
         'Food & Dining': 'Φαγητό + εστιατόρια',
         'Multimedia Design': 'Σχεδίαση πολυμέσων',
         Medical: 'Ιατρική',
         Music: 'Μουσική',
         'Navigation & Maps': 'Πλοήγηση + χάρτες',
         'News & Weather': 'Ειδήσεις + καιρός',
         'Personal Finance': 'Οικονομική διαχείριση',
         'Photo & video': 'Φωτογραφία + βίντεο',
         Productivity: 'Παραγωγικότητα',
         Security: 'Ασφάλεια',
         Shopping: 'Αγορές',
         Social: 'Κοινωνικά δίκτυα',
         Sports: 'Αθλητικά',
         Travel: 'Ταξίδια',
         'Utilities & tools': 'Βοηθητικά προγράμματα + εργαλεία',
         Games: 'Παιχνίδια',
         Personalization: 'Εξατομίκευση',
         Other: 'Άλλο',
         IAP: 'Αγορά εντός εφαρμογής',
         'Paid Apps': 'Εφαρμογές επί πληρωμή',
         'APAC': 'Ασία-Ειρηνικός',
         'Canada': 'Καναδάς',
         'Central and Eastern Europe': 'Κεντρική και Ανατολική Ευρώπη',
         'France': 'Γαλλία',
         'Germany': 'Γερμανία',
         'Greater China': 'Ευρύτερη Κίνα',
         'India': 'Ινδία',
         'Japan': 'Ιαπωνία',
         'Latam': 'Λατινική Αμερική',
         'MEA': 'Μέση Ανατολή και Αφρική',
         'UK': 'Η.Β.',
         'United States': 'Ηνωμένες Πολιτείες',
         'Western Europe': 'Δυτική Ευρώπη',
         'World': 'Παγκοσμίως'
      },
      'en-us':
      {
         Jan: 'Jan $2',
         Feb: 'Feb $2',
         Mar: 'Mar $2',
         Apr: 'Apr $2',
         May: 'May $2',
         Jun: 'Jun $2',
         Jul: 'Jul $2',
         Aug: 'Aug $2',
         Sep: 'Sep $2',
         Oct: 'Oct $2',
         Nov: 'Nov $2',
         Dec: 'Dec $2',
         'Books & Reference': 'Books & Reference',
         Business: 'Business',
         Education: 'Education',
         Entertainment: 'Entertainment',
         'Food & Dining': 'Food & Dining',
         Games: 'Games',
         'Government & Politics': 'Government & Politics',
         'Health & Fitness': 'Health & Fitness',
         'Lifestyle': 'Lifestyle',
         'Music': 'Music',
         'News & Weather': 'News & Weather',
         'Personal Finance': 'Personal Finance',
         'Photo & video': 'Photo & video',
         Productivity: 'Productivity',
         Security: 'Security',
         Shopping: 'Shopping',
         Social: 'Social',
         Sports: 'Sports',
         Travel: 'Travel',
         'Utilities & tools': 'Utilities & tools',
         'Developer Tools': 'Developer Tools',
         'Kids & Family': 'Kids & Family',
         'Medical': 'Medical',
         'Multimedia Design': 'Multimedia Design',
         'Navigation & Maps': 'Navigation & Maps',
         Personalization: 'Personalization',
         Other: 'Other',
         IAP: 'IAP',
         'Paid Apps': 'Paid Apps',
         'APAC': 'APAC',
         'Canada': 'Canada',
         'Central and Eastern Europe': 'Central and Eastern Europe',
         'France': 'France',
         'Germany': 'Germany',
         'Greater China': 'Greater China',
         'India': 'India',
         'Japan': 'Japan',
         'Latam': 'Latam',
         'MEA': 'MEA',
         'UK': 'UK',
         'United States': 'United States',
         'Western Europe': 'Western Europe',
         'World': 'World'
      },
      'es-es':
      {
         Jan: 'Ene $2',
         Feb: 'Feb $2',
         Mar: 'Mar $2',
         Apr: 'Abr $2',
         May: 'May $2',
         Jun: 'Jun $2',
         Jul: 'Jul $2',
         Aug: 'Ago $2',
         Sep: 'Sep $2',
         Oct: 'Oct $2',
         Nov: 'Nov $2',
         Dec: 'Dic $2',
         'Books & Reference': 'Libros y referencia',
         Business: 'Empresa',
         'Developer Tools': 'Herramientas de desarrollo',
         Education: 'Educación',
         Entertainment: 'Entretenimiento',
         'Government & Politics': 'Gobierno y política',
         'Health & Fitness': 'Salud y bienestar',
         'Kids & Family': 'Niños y familia',
         Lifestyle: 'Estilo de vida',
         'Food & Dining': 'Bares y restaurantes',
         'Multimedia Design': 'Diseño multimedia',
         Medical: 'Medicina',
         Music: 'Música',
         'Navigation & Maps': 'Navegación y mapas',
         'News & Weather': 'Noticias y tiempo',
         'Personal Finance': 'Finanzas personales',
         'Photo & video': 'Fotos y vídeos',
         Productivity: 'Productividad',
         Security: 'Seguridad',
         Shopping: 'Compras',
         Social: 'Redes sociales',
         Sports: 'Deportes',
         Travel: 'Viajes',
         'Utilities & tools': 'Utilidades y herramientas',
         Games: 'Juegos',
         Personalization: 'Personalización',
         Other: 'Otros',
         IAP: 'IAP',
         'Paid Apps': 'Aplicaciones de pago',
         'APAC': 'APAC',
         'Canada': 'Canadá',
         'Central and Eastern Europe': 'Europa Central y Oriental',
         'France': 'Francia',
         'Germany': 'Alemania',
         'Greater China': 'China, Hong Kong y Taiwán',
         'India': 'India',
         'Japan': 'Japón',
         'Latam': 'Latinoamérica',
         'MEA': 'MEA',
         'UK': 'ReinoUnido',
         'United States': 'Estados Unidos',
         'Western Europe': 'Europa Occidental',
         'World': 'Internacional'
      },
      'fi-fi':
      {
         Jan: 'tammi $2',
         Feb: 'helmi $2',
         Mar: 'maalis $2',
         Apr: 'huhti $2',
         May: 'touko $2',
         Jun: 'kesä $2',
         Jul: 'heinä $2',
         Aug: 'elo $2',
         Sep: 'syys $2',
         Oct: 'loka $2',
         Nov: 'marras $2',
         Dec: 'joulu $2',
         'Books & Reference': 'Kirjat ja lähdeaineistot',
         Business: 'Yritystoiminta',
         'Developer Tools': 'Kehittäjien työkalut',
         Education: 'Koulutus',
         Entertainment: 'Viihde',
         'Government & Politics': 'Hallinto ja politiikka',
         'Health & Fitness': 'Terveys ja kuntoilu',
         'Kids & Family': 'Lapset ja perhe',
         Lifestyle: 'Harrasteet',
         'Food & Dining': 'Ruoka ja ruokailu',
         'Multimedia Design': 'Multimediasuunnittelu',
         Medical: 'Terveys',
         Music: 'Musiikki',
         'Navigation & Maps': 'Kartat ja navigointi',
         'News & Weather': 'Uutiset ja sää',
         'Personal Finance': 'Oma taloudenhoito',
         'Photo & video': 'Valokuvat ja videot',
         Productivity: 'Tuottavuus',
         Security: 'Tietoturva',
         Shopping: 'Shoppailu',
         Social: 'Yhteisöpalvelut',
         Sports: 'Urheilu',
         Travel: 'Matkailu',
         'Utilities & tools': 'Työkalut ja hyötyohjelmat',
         Games: 'Pelit',
         Personalization: 'Mukauttaminen',
         Other: 'Muut',
         IAP: 'Sovelluskohtainen tuote',
         'Paid Apps': 'Maksulliset sovellukset',
         'APAC': 'Aasian ja Tyynenmeren alue',
         'Canada': 'Kanada',
         'Central and Eastern Europe': 'Keski- ja Itä-Eurooppa',
         'France': 'Ranska',
         'Germany': 'Saksa',
         'Greater China': 'Suur-Kiina',
         'India': 'Intia',
         'Japan': 'Japani',
         'Latam': 'Latinalainen Amerikka',
         'MEA': 'Lähi-itä ja Afrikka',
         'UK': 'Yhdistynyt kuningaskunta',
         'United States': 'Yhdysvallat',
         'Western Europe': 'Länsi-Eurooppa',
         'World': 'Maapallo'
      },
      'fr-fr':
      {
         Jan: 'Jan $2',
         Feb: 'Fév $2',
         Mar: 'Mars $2',
         Apr: 'Avr $2',
         May: 'Mai $2',
         Jun: 'Juin $2',
         Jul: 'Juil $2',
         Aug: 'Août $2',
         Sep: 'Sept $2',
         Oct: 'Oct $2',
         Nov: 'Nov $2',
         Dec: 'Déc $2',
         'Books & Reference': 'Livres + référence',
         Business: 'Entreprise',
         'Developer Tools': 'Outils de développement',
         Education: 'Éducation',
         Entertainment: 'Divertissement',
         'Government & Politics': 'Gouvernement + politique',
         'Health & Fitness': 'Forme + santé',
         'Kids & Family': 'Enfants + famille',
         Lifestyle: 'Loisirs',
         'Food & Dining': 'Alimentation + cuisine',
         'Multimedia Design': 'Conception multimédia',
         Medical: 'Médical',
         Music: 'Musique',
         'Navigation & Maps': 'Navigation + cartes',
         'News & Weather': 'Actualités + météo',
         'Personal Finance': 'Finances personnelles',
         'Photo & video': 'Photo + vidéo',
         Productivity: 'Productivité',
         Security: 'Sécurité',
         Shopping: 'Achats',
         Social: 'Social',
         Sports: 'Sports',
         Travel: 'Voyage',
         'Utilities & tools': 'Utilitaires + outils',
         Games: 'Jeux',
         Personalization: 'Personnalisation',
         Other: 'Autre',
         IAP: 'Produit in-app',
         'Paid Apps': 'Applications payantes',
         'APAC': 'APAC',
         'Canada': 'Canada',
         'Central and Eastern Europe': 'Europe centrale et de l\'Est',
         'France': 'France',
         'Germany': 'Allemagne',
         'Greater China': 'Chine populaire',
         'India': 'Inde',
         'Japan': 'Japon',
         'Latam': 'Amérique latine',
         'MEA': 'MEA',
         'UK': 'RU',
         'United States': 'États-Unis',
         'Western Europe': 'Europe de l\'Ouest',
         'World': 'Monde'
      },
      'he-il':
      {
         Jan: "ינו' $2",
         Feb: "פבר' $2",
         Mar: "מרץ $2",
         Apr: "אפר' $2",
         May: "מאי $2",
         Jun: "יונ' $2",
         Jul: "יול' $2",
         Aug: "אוג' $2",
         Sep: "ספט' $2",
         Oct: "אוק' $2",
         Nov: "נוב' $2",
         Dec: "דצמ' $2",
         'Books & Reference': 'ספרים וחומר עזר',
         Business: 'עסקים',
         'Developer Tools': 'כלי פיתוח',
         Education: 'חינוך',
         Entertainment: 'בידור',
         'Government & Politics': 'ממשל ופוליטיקה',
         'Health & Fitness': 'בריאות וכושר',
         'Kids & Family': 'ילדים + משפחה',
         Lifestyle: 'לייפסטייל',
         'Food & Dining': 'אוכל ומסעדות',
         'Multimedia Design': 'עיצוב מולטימדיה',
         Medical: 'בריאות',
         Music: 'מוסיקה',
         'Navigation & Maps': 'ניווט ומפות',
         'News & Weather': 'חדשות ומזג אוויר',
         'Personal Finance': 'כספים אישיים',
         'Photo & video': 'תמונות וסרטים',
         Productivity: 'יעילות',
         Security: 'אבטחה',
         Shopping: 'קניות',
         Social: 'חברתי',
         Sports: 'ספורט',
         Travel: 'נסיעות',
         'Utilities & tools': 'כלי עזר וכלים',
         Games: 'משחקים',
         Personalization: 'התאמה אישית',
         Other: 'אחר',
         IAP: 'רכישה בתוך אפליקציה',
         'Paid Apps': 'אפליקציות בתשלום',
         'APAC': 'APAC',
         'Canada': 'קנדה',
         'Central and Eastern Europe': 'מרכז ומזרח אירופה',
         'France': 'צרפת',
         'Germany': 'גרמניה',
         'Greater China': 'סין רבתי',
         'India': 'הודו',
         'Japan': 'יפן',
         'Latam': 'אמל" ט',
         'MEA': 'MEA',
         'UK': 'בריטניה',
         'United States': 'ארצות הברית',
         'Western Europe': 'מערב אירופה',
         'World': 'עולם'
      },
      'hu-hu':
      {
         Jan: 'Jan $2',
         Feb: 'Feb $2',
         Mar: 'Márc $2',
         Apr: 'Ápr $2',
         May: 'Máj $2',
         Jun: 'Jún $2',
         Jul: 'Júl $2',
         Aug: 'Aug $2',
         Sep: 'Szep $2',
         Oct: 'Okt $2',
         Nov: 'Nov $2',
         Dec: 'Dec $2',
         'Books & Reference': 'Könyvek és referenciák',
         Business: 'Üzlet',
         'Developer Tools': 'Fejlesztői eszközök',
         Education: 'Oktatás',
         Entertainment: 'Szórakozás',
         'Government & Politics': 'Közigazgatás és politika',
         'Health & Fitness': 'Egészség és fitnesz',
         'Kids & Family': 'Gyermekek és család',
         Lifestyle: 'Életmód',
         'Food & Dining': 'Gasztronómia',
         'Multimedia Design': 'Multimédiás dizájn',
         Medical: 'Egészségügy',
         Music: 'Zene',
         'Navigation & Maps': 'Navigáció és térképek',
         'News & Weather': 'Hírek és időjárás',
         'Personal Finance': 'Személyes pénzügyek',
         'Photo & video': 'Fotó és videó',
         Productivity: 'Irodai alkalmazások',
         Security: 'Biztonság',
         Shopping: 'Vásárlás',
         Social: 'Közösségi',
         Sports: 'Sport',
         Travel: 'Utazás',
         'Utilities & tools': 'Segédprogramok',
         Games: 'Játékok',
         Personalization: 'Személyre szabás',
         Other: 'Egyéb',
         IAP: 'alkalmazáson belüli vásárlás',
         'Paid Apps': 'Fizetős alkalmazások',
         'APAC': 'Ázsia és a Csendes-óceáni térség',
         'Canada': 'Kanada',
         'Central and Eastern Europe': 'Közép- és Kelet-Európa',
         'France': 'Franciaország',
         'Germany': 'Németország',
         'Greater China': 'Nagy-Kína',
         'India': 'India',
         'Japan': 'Japán',
         'Latam': 'Latin-Amerika',
         'MEA': '',
         'UK': 'Egyesült Királyság',
         'United States': 'Egyesült Államok',
         'Western Europe': 'Nyugat-Európa',
         'World': 'Globális'
      },
      'it-it':
      {
         Jan: 'Gen $2',
         Feb: 'Feb $2',
         Mar: 'Mar $2',
         Apr: 'Apr $2',
         May: 'Mag $2',
         Jun: 'Giu $2',
         Jul: 'Lug $2',
         Aug: 'Ago $2',
         Sep: 'Set $2',
         Oct: 'Ott $2',
         Nov: 'Nov $2',
         Dec: 'Dic $2',
         'Books & Reference': 'Libri e manuali',
         Business: 'Lavoro',
         'Developer Tools': 'Strumenti di sviluppo',
         Education: 'Formazione',
         Entertainment: 'Intrattenimento',
         'Government & Politics': 'Governo e politica',
         'Health & Fitness': 'Salute e benessere',
         'Kids & Family': 'Bambini e famiglia',
         Lifestyle: 'Lifestyle',
         'Food & Dining': 'Ristoranti e bar',
         'Multimedia Design': 'Progettazione multimediale',
         Medical: 'Medicina',
         Music: 'Musica',
         'Navigation & Maps': 'Navigatori e cartine',
         'News & Weather': 'Notizie e meteo',
         'Personal Finance': 'Finanza personale',
         'Photo & video': 'Foto e video',
         Productivity: 'Produttività',
         Security: 'Sicurezza',
         Shopping: 'Shopping',
         Social: 'Social network',
         Sports: 'Sport',
         Travel: 'Viaggi',
         'Utilities & tools': 'Utilità e strumenti',
         Games: 'Giochi',
         Personalization: 'Personalizzazione',
         Other: 'Altro',
         IAP: 'Acquisto in-app',
         'Paid Apps': 'App a pagamento',
         'APAC': 'APAC',
         'Canada': 'Canada',
         'Central and Eastern Europe': 'Europa centrale e orientale',
         'France': 'Francia',
         'Germany': 'Germania',
         'Greater China': 'Cina continentale',
         'India': 'India',
         'Japan': 'Giappone',
         'Latam': 'America Latina',
         'MEA': 'MEA',
         'UK': 'Regno Unito',
         'United States': 'Stati Uniti',
         'Western Europe': 'Europa occidentale',
         'World': 'Mondo'
      },
      'ja-jp':
      {
         Jan: '$2 1 月',
         Feb: '$2 2 月',
         Mar: '$2 3 月',
         Apr: '$2 4 月',
         May: '$2 5 月',
         Jun: '$2 6 月',
         Jul: '$2 7 月',
         Aug: '$2 8 月',
         Sep: '$2 9 月',
         Oct: '$2 10 月',
         Nov: '$2 11 月',
         Dec: '$2 12 月',
         'Books & Reference': '書籍 &amp; 参考資料',
         Business: '会社',
         'Developer Tools': '開発者ツール',
         Education: '教育',
         Entertainment: 'エンターテイメント',
         'Government & Politics': '行政 &amp; 政治',
         'Health & Fitness': 'ヘルスケア &amp; フィットネス',
         'Kids & Family': '家族 &amp; 子供',
         Lifestyle: 'ライフスタイル',
         'Food & Dining': 'グルメ',
         'Multimedia Design': 'マルチメディア デザイン',
         Medical: '医療',
         Music: '音楽',
         'Navigation & Maps': 'ナビゲーション &amp; マップ',
         'News & Weather': 'ニュース &amp; 天気',
         'Personal Finance': 'パーソナル ファイナンス',
         'Photo & video': '写真 &amp; ビデオ',
         Productivity: '仕事効率化',
         Security: 'セキュリティ',
         Shopping: 'ショッピング',
         Social: 'ソーシャル',
         Sports: 'スポーツ',
         Travel: '旅行',
         'Utilities & tools': 'ユーティリティ &amp; ツール',
         Games: 'ゲーム',
         Personalization: '個人設定',
         Other: 'その他',
         IAP: 'IAP',
         'Paid Apps': '有料アプリ',
         'APAC': 'APAC',
         'Canada': 'カナダ',
         'Central and Eastern Europe': '中央および東ヨーロッパ',
         'France': 'フランス',
         'Germany': 'ドイツ',
         'Greater China': '中国 ',
         'India': 'インド',
         'Japan': '日本',
         'Latam': 'ラテンアメリカ',
         'MEA': 'MEA',
         'UK': 'イギリス',
         'United States': '米国',
         'Western Europe': '西ヨーロッパ',
         'World': '世界'
      },
      'ko-kr':
      {
         Jan: '1월 $2',
         Feb: '2월 $2',
         Mar: '3월 $2',
         Apr: '4월 $2',
         May: '5월 $2',
         Jun: '6월 $2',
         Jul: '7월 $2',
         Aug: '8월 $2',
         Sep: '9월 $2',
         Oct: '10월 $2',
         Nov: '11월 $2',
         Dec: '12월 $2',
         'Books & Reference': '책 + 참고자료',
         Business: '비즈니스',
         'Developer Tools': '개발자 도구',
         Education: '교육',
         Entertainment: '엔터테인먼트',
         'Government & Politics': '정부 + 정치',
         'Health & Fitness': '건강 + 피트니스',
         'Kids & Family': '어린이 + 가족',
         Lifestyle: '라이프스타일',
         'Food & Dining': '추천 음식점',
         'Multimedia Design': '멀티미디어 디자인',
         Medical: '의료',
         Music: '음악',
         'Navigation & Maps': '내비게이션 + 지도',
         'News & Weather': '뉴스 + 날씨',
         'Personal Finance': '금융',
         'Photo & video': '사진 + 동영상',
         Productivity: '생산성',
         Security: '보안',
         Shopping: '쇼핑',
         Social: '소셜',
         Sports: '스포츠',
         Travel: '여행',
         'Utilities & tools': '유틸리티 + 도구',
         Games: '게임',
         Personalization: '개인 설정',
         Other: '기타',
         IAP: 'IAP(앱에서 바로 구매)',
         'Paid Apps': '유료 앱',
         'APAC': 'APAC',
         'Canada': '캐나다',
         'Central and Eastern Europe': '유럽 중부 및 동부',
         'France': '프랑스',
         'Germany': '독일',
         'Greater China': '중화권 국가',
         'India': '인도',
         'Japan': '일본',
         'Latam': '라틴 아메리카',
         'MEA': 'MEA',
         'UK': '영국',
         'United States': '미국',
         'Western Europe': '서유럽',
         'World': '세계'
      },
      'nb-no':
      {
         Jan: 'Jan $2',
         Feb: 'Feb $2',
         Mar: 'Mar $2',
         Apr: 'Apr $2',
         May: 'Mai $2',
         Jun: 'Jun $2',
         Jul: 'Jul $2',
         Aug: 'Aug $2',
         Sep: 'Sep $2',
         Oct: 'Okt $2',
         Nov: 'Nov $2',
         Dec: 'Des $2',
         'Books & Reference': 'Bøker og referanser',
         Business: 'Forretninger',
         'Developer Tools': 'Utviklerverktøy',
         Education: 'Utdanning',
         Entertainment: 'Underholdning',
         'Government & Politics': 'Myndigheter og politikk',
         'Health & Fitness': 'Helse og trening',
         'Kids & Family': 'Familie og barn',
         Lifestyle: 'Livsstil',
         'Food & Dining': 'Mat og restauranter',
         'Multimedia Design': 'Multimediedesign',
         Medical: 'Medisinsk',
         Music: 'Musikk',
         'Navigation & Maps': 'Navigasjon og kart',
         'News & Weather': 'Nyheter og vær',
         'Personal Finance': 'Personlig økonomi',
         'Photo & video': 'Bilde og video',
         Productivity: 'Produktivitet',
         Security: 'Sikkerhet',
         Shopping: 'Shopping',
         Social: 'Sosialt',
         Sports: 'Sport',
         Travel: 'Reise',
         'Utilities & tools': 'Utstyr og verktøy',
         Games: 'Spill',
         Personalization: 'Personlig tilpassing',
         Other: 'Annet',
         IAP: 'Appinternt kjøp',
         'Paid Apps': 'Betalte apper',
         'APAC': 'Øst-Asia og Stillehavsregionen',
         'Canada': 'Canada',
         'Central and Eastern Europe': 'Sentral- og Øst-Europa',
         'France': 'Frankrike',
         'Germany': 'Tyskland',
         'Greater China': 'Kina-regionen',
         'India': 'India',
         'Japan': 'Japan',
         'Latam': 'Latin-Amerika',
         'MEA': 'Midtøsten og Afrika',
         'UK': 'Storbritannia',
         'United States': 'USA',
         'Western Europe': 'Vest-Europa',
         'World': 'Verden'
      },
      'nl-nl':
      {
         Jan: 'Jan $2',
         Feb: 'Feb $2',
         Mar: 'Mrt $2',
         Apr: 'Apr $2',
         May: 'Mei $2',
         Jun: 'Jun $2',
         Jul: 'Jul $2',
         Aug: 'Aug $2',
         Sep: 'Sep $2',
         Oct: 'Okt $2',
         Nov: 'Nov $2',
         Dec: 'Dec $2',
         'Books & Reference': 'Boeken en referentie',
         Business: 'Business',
         'Developer Tools': 'Ontwikkelhulpprogramma\'s',
         Education: 'Opleiding',
         Entertainment: 'Entertainment',
         'Government & Politics': 'Regering en politiek',
         'Health & Fitness': 'Gezondheid en fitness',
         'Kids & Family': 'Kinderen en gezin',
         Lifestyle: 'Lifestyle',
         'Food & Dining': 'Eten en drinken',
         'Multimedia Design': 'Multimediadesign',
         Medical: 'Medisch',
         Music: 'Muziek',
         'Navigation & Maps': 'Navigatie en kaarten',
         'News & Weather': 'Nieuws en weer',
         'Personal Finance': 'Persoonlijke financiën',
         'Photo & video': 'Foto en video',
         Productivity: 'Productiviteit',
         Security: 'Beveiliging',
         Shopping: 'Winkelen',
         Social: 'Sociaal',
         Sports: 'Sport',
         Travel: 'Reizen',
         'Utilities & tools': 'Hulpprogramma\'s en tools',
         Games: 'Ontspanning',
         Personalization: 'Aanpassingen',
         Other: 'Anders',
         IAP: 'in-app-aankoop',
         'Paid Apps': 'Betaalde apps',
         'APAC': 'APAC',
         'Canada': 'Canada',
         'Central and Eastern Europe': 'Centraal en Oost-Europa',
         'France': 'Frankrijk',
         'Germany': 'Duitsland',
         'Greater China': 'Groter China',
         'India': 'India',
         'Japan': 'Japan',
         'Latam': 'LATAM',
         'MEA': 'MEA',
         'UK': 'Verenigd Koninkrijk',
         'United States': 'Verenigde Staten',
         'Western Europe': 'West-Europa',
         'World': 'Wereld'
      },
      'pl-pl':
      {
         Jan: 'Sty $2',
         Feb: 'Lut $2',
         Mar: 'Mar $2',
         Apr: 'Kwi $2',
         May: 'Maj $2',
         Jun: 'Cze $2',
         Jul: 'Lip $2',
         Aug: 'Sie $2',
         Sep: 'Wrz $2',
         Oct: 'Paź $2',
         Nov: 'Lis $2',
         Dec: 'Gru $2',
         'Books & Reference': 'Książki i podręczniki',
         Business: 'Biznes',
         'Developer Tools': 'Narzędzia programistyczne',
         Education: 'Edukacja',
         Entertainment: 'Rozrywka',
         'Government & Politics': 'Rząd i polityka',
         'Health & Fitness': 'Zdrowie i fitness',
         'Kids & Family': 'Dla dzieci i familijne',
         Lifestyle: 'Styl życia',
         'Food & Dining': 'Jedzenie i gotowanie',
         'Multimedia Design': 'Tworzenie multimediów',
         Medical: 'Medycyna',
         Music: 'Muzyka',
         'Navigation & Maps': 'Nawigacja i mapy',
         'News & Weather': 'Wiadomości i pogoda',
         'Personal Finance': 'Finanse osobiste',
         'Photo & video': 'Zdjęcia i filmy',
         Productivity: 'Organizacja zadań',
         Security: 'Zabezpieczenia',
         Shopping: 'Zakupy',
         Social: 'Społecznościowe',
         Sports: 'Sport',
         Travel: 'Podróże',
         'Utilities & tools': 'Narzędzia',
         Games: 'Gry',
         Personalization: 'Personalizacja',
         Other: 'Inne',
         IAP: 'Zakup w aplikacji',
         'Paid Apps': 'Płatne aplikacje',
         'APAC': 'Azja i Pacyfik',
         'Canada': 'Kanada',
         'Central and Eastern Europe': 'Europa Środkowa i Wschodnia',
         'France': 'Francja',
         'Germany': 'Niemcy',
         'Greater China': 'Chiny',
         'India': 'Indie',
         'Japan': 'Japonia',
         'Latam': 'Ameryka Łacińska',
         'MEA': 'Bliski Wschód i Afryka',
         'UK': 'Zjednoczone Królestwo',
         'United States': 'Stany Zjednoczone',
         'Western Europe': 'Europa Zachodnia',
         'World': 'Świat'
      },
      'pt-br':
      {
         Jan: 'Jan $2',
         Feb: 'Fev $2',
         Mar: 'Mar $2',
         Apr: 'Abr $2',
         May: 'Mai $2',
         Jun: 'Jun $2',
         Jul: 'Jul $2',
         Aug: 'Ago $2',
         Sep: 'Set $2',
         Oct: 'Out $2',
         Nov: 'Nov $2',
         Dec: 'Dez $2',
         'Books & Reference': 'Livros e referências',
         Business: 'Negócios',
         'Developer Tools': 'Ferramentas de desenvolvedor',
         Education: 'Educação',
         Entertainment: 'Entretenimento',
         'Government & Politics': 'Governo e política',
         'Health & Fitness': 'Saúde e bem-estar',
         'Kids & Family': 'Crianças + família',
         Lifestyle: 'Estilo de Vida',
         'Food & Dining': 'Bares e Restaurantes',
         'Multimedia Design': 'Design multimídia',
         Medical: 'Medicina',
         Music: 'Música',
         'Navigation & Maps': 'Navegação e mapas',
         'News & Weather': 'Notícias e Meteorologia',
         'Personal Finance': 'Finanças pessoais',
         'Photo & video': 'Foto e vídeo',
         Productivity: 'Produtividade',
         Security: 'Segurança',
         Shopping: 'Compras',
         Social: 'Redes Sociais',
         Sports: 'Esportes',
         Travel: 'Viagem',
         'Utilities & tools': 'Utilitários e ferramentas',
         Games: 'Jogos',
         Personalization: 'Personalização',
         Other: 'Outros',
         IAP: 'IAP',
         'Paid Apps': 'Aplicativos pagos',
         'APAC': 'Região da Ásia - Pacífico',
         'Canada': 'Canadá',
         'Central and Eastern Europe': 'Europa central e Leste Europeu',
         'France': 'França',
         'Germany': 'Alemanha',
         'Greater China': 'Grande China',
         'India': 'Índia',
         'Japan': 'Japão',
         'Latam': 'América latina',
         'MEA': 'África e Oriente Médio',
         'UK': 'Reino Unido',
         'United States': 'Estados Unidos',
         'Western Europe': 'Europa Ocidental',
         'World': 'Mundo'
      },
      'pt-pt':
      {
         Jan: 'Jan $2',
         Feb: 'Fev $2',
         Mar: 'Mar $2',
         Apr: 'Abr $2',
         May: 'Mai $2',
         Jun: 'Jun $2',
         Jul: 'Jul $2',
         Aug: 'Ago $2',
         Sep: 'Set $2',
         Oct: 'Out $2',
         Nov: 'Nov $2',
         Dec: 'Dez $2',
         'Books & Reference': 'Livros + consulta',
         Business: 'Negócios',
         'Developer Tools': 'Ferramentas de programação',
         Education: 'Educação',
         Entertainment: 'Entretenimento',
         'Government & Politics': 'Governo + política',
         'Health & Fitness': 'Saúde + bem-estar',
         'Kids & Family': 'Crianças + família',
         Lifestyle: 'Estilo de vida',
         'Food & Dining': 'Alimentação + restauração',
         'Multimedia Design': 'Design multimédia',
         Medical: 'Medicina',
         Music: 'Música',
         'Navigation & Maps': 'Navegação + mapas',
         'News & Weather': 'Notícias + meteorologia',
         'Personal Finance': 'Finanças pessoais',
         'Photo & video': 'Fotografia + vídeo',
         Productivity: 'Produtividade',
         Security: 'Segurança',
         Shopping: 'Compras',
         Social: 'Social',
         Sports: 'Desporto',
         Travel: 'Viagens',
         'Utilities & tools': 'Utilitários + ferramentas',
         Games: 'Jogos',
         Personalization: 'Personalização',
         Other: 'Outros',
         IAP: 'IAP',
         'Paid Apps': 'Aplicações Pagas',
         'APAC': 'Ásia-Pacífico',
         'Canada': 'Canadá',
         'Central and Eastern Europe': 'Europa Central e de Leste',
         'France': 'França',
         'Germany': 'Alemanha',
         'Greater China': 'Grande China',
         'India': 'Índia',
         'Japan': 'Japão',
         'Latam': 'América Latina',
         'MEA': 'Médio-Oriente e África',
         'UK': 'Reino Unido',
         'United States': 'Estados Unidos',
         'Western Europe': 'Europa Ocidental',
         'World': 'Mundo'
      },
      'ru-ru':
      {
         Jan: 'Янв $2',
         Feb: 'Фев $2',
         Mar: 'Мар $2',
         Apr: 'Апр $2',
         May: 'Май $2',
         Jun: 'Июн $2',
         Jul: 'Июл $2',
         Aug: 'Авг $2',
         Sep: 'Сен $2',
         Oct: 'Окт $2',
         Nov: 'Ноя $2',
         Dec: 'Дек $2',
         'Books & Reference': 'Книги + Справочные материалы',
         Business: 'Бизнес',
         'Developer Tools': 'Инструменты разработчика',
         Education: 'Образование',
         Entertainment: 'Развлечения',
         'Government & Politics': 'Государственное управление + Политика',
         'Health & Fitness': 'Здоровье + Фитнес',
         'Kids & Family': 'Дети+семья',
         Lifestyle: 'Образ жизни',
         'Food & Dining': 'Еда + Питание',
         'Multimedia Design': 'Дизайн мультимедиа',
         Medical: 'Медицинские',
         Music: 'Музыка',
         'Navigation & Maps': 'Навигация + Карты',
         'News & Weather': 'Новости + Погода',
         'Personal Finance': 'Личные финансы',
         'Photo & video': 'Фото + Видео',
         Productivity: 'Производительность',
         Security: 'Безопасность',
         Shopping: 'Покупки',
         Social: 'Социальные',
         Sports: 'Спорт',
         Travel: 'Путешествия',
         'Utilities & tools': 'Утилиты + Инструменты',
         Games: 'Игры',
         Personalization: 'Персонализация',
         Other: 'Другие',
         IAP: 'IAP',
         'Paid Apps': 'Платные приложения',
         'APAC': 'Азиатско-Тихоокеанский регион',
         'Canada': 'Канада',
         'Central and Eastern Europe': 'Центральная и Восточная Европа',
         'France': 'Франция',
         'Germany': 'Германия',
         'Greater China': 'Большой Китай',
         'India': 'Индия',
         'Japan': 'Япония',
         'Latam': 'Латинская Америка',
         'MEA': 'Средний Восток и Африка',
         'UK': 'Соединенное Королевство',
         'United States': 'США',
         'Western Europe': 'Западная Европа',
         'World': 'Мир'
      },
      'sv-se':
      {
         Jan: 'jan $2',
         Feb: 'feb $2',
         Mar: 'mar $2',
         Apr: 'apr $2',
         May: 'maj $2',
         Jun: 'jun $2',
         Jul: 'jul $2',
         Aug: 'aug $2',
         Sep: 'sep $2',
         Oct: 'okt $2',
         Nov: 'nov $2',
         Dec: 'dec $2',
         'Books & Reference': 'Böcker + referenser',
         Business: 'Företag',
         'Developer Tools': 'Utvecklarverktyg',
         Education: 'Utbildning',
         Entertainment: 'Underhållning',
         'Government & Politics': 'Myndigheter + politik',
         'Health & Fitness': 'Hälsa + träning',
         'Kids & Family': 'Familj + barn',
         Lifestyle: 'Livsstil',
         'Food & Dining': 'Mat + dryck',
         'Multimedia Design': 'Multimediedesign デザイン',
         Medical: 'Medicinskt',
         Music: 'Musik',
         'Navigation & Maps': 'Navigering + kartor',
         'News & Weather': 'Nyheter + väder',
         'Personal Finance': 'Privatekonomi',
         'Photo & video': 'Foto + video',
         Productivity: 'Produktivitet',
         Security: 'Säkerhet',
         Shopping: 'Shopping',
         Social: 'Sociala medier',
         Sports: 'Sport',
         Travel: 'Resor',
         'Utilities & tools': 'Verktyg',
         Games: 'Spel',
         Personalization: 'Anpassning',
         Other: 'Övriga',
         IAP: 'IAP',
         'Paid Apps': 'Betalappar',
         'APAC': 'APAC',
         'Canada': 'Kanada',
         'Central and Eastern Europe': 'Central- och östeuropa',
         'France': 'Frankrike',
         'Germany': 'Tyskland',
         'Greater China': 'Kina-regionen',
         'India': 'Indien',
         'Japan': 'Japan',
         'Latam': 'Latam',
         'MEA': 'MEA',
         'UK': 'Storbritannien och Nordirland',
         'United States': 'USA',
         'Western Europe': 'Västeuropa',
         'World': 'Världen'
      },
      'zh-cn':
      {
         Jan: '一月 $2',
         Feb: '二月 $2',
         Mar: '三月 $2',
         Apr: '四月 $2',
         May: '五月 $2',
         Jun: '六月 $2',
         Jul: '七月 $2',
         Aug: '八月 $2',
         Sep: '九月 $2',
         Oct: '十月 $2',
         Nov: '十一月 $2',
         Dec: '十二月 $2',
         'Books & Reference': '书籍 + 参考',
         Business: '商务',
         'Developer Tools': '开发人员工具',
         Education: '教育',
         Entertainment: '娱乐',
         'Government & Politics': '政府 + 政治',
         'Health & Fitness': '健康 + 健身',
         'Kids & Family': '孩子 + 家庭',
         Lifestyle: '生活方式',
         'Food & Dining': '食品 + 餐饮',
         'Multimedia Design': '多媒体设计',
         Medical: '医疗',
         Music: '音乐',
         'Navigation & Maps': '导航 + 地图',
         'News & Weather': '新闻 + 天气',
         'Personal Finance': '个人理财',
         'Photo & video': '照片 + 视频',
         Productivity: '生产率',
         Security: '安全性',
         Shopping: '购物',
         Social: '社交',
         Sports: '体育',
         Travel: '旅游',
         'Utilities & tools': '实用工具 + 工具',
         Games: '游戏',
         Personalization: '个性化',
         Other: '其他',
         IAP: '应用内购买',
         'Paid Apps': '付费应用',
         'APAC': '亚太地区',
         'Canada': '加拿大',
         'Central and Eastern Europe': '中欧和东欧',
         'France': '法国',
         'Germany': '德国',
         'Greater China': '大中华区',
         'India': '印度',
         'Japan': '日本',
         'Latam': '拉丁美洲',
         'MEA': '中东亚地区',
         'UK': '英国',
         'United States': '美国',
         'Western Europe': '西欧',
         'World': '世界'
      },
      'zh-tw':
      {
         Jan: '一月 $2',
         Feb: '二月 $2',
         Mar: '三月 $2',
         Apr: '四月 $2',
         May: '五月 $2',
         Jun: '六月 $2',
         Jul: '七月 $2',
         Aug: '八月 $2',
         Sep: '九月 $2',
         Oct: '十月 $2',
         Nov: '十一月 $2',
         Dec: '十二月 $2',
         'Books & Reference': '書籍 + 參考',
         Business: '商業',
         'Developer Tools': '開發人員工具',
         Education: '教育',
         Entertainment: '娛樂',
         'Government & Politics': '政府 + 政治',
         'Health & Fitness': '健康 + 健身',
         'Kids & Family': '親子 + 家庭',
         Lifestyle: '生活方式',
         'Food & Dining': '飲食 + 餐飲',
         'Multimedia Design': '多媒體設計',
         Medical: '醫療',
         Music: '音樂',
         'Navigation & Maps': '導航 + 地圖',
         'News & Weather': '新聞 + 氣象',
         'Personal Finance': '個人理財',
         'Photo & video': '照片 + 影片',
         Productivity: '生產力',
         Security: '安全性',
         Shopping: '購物',
         Social: '社交',
         Sports: '體育',
         Travel: '旅遊',
         'Utilities & tools': '公用程式 + 工具',
         Games: '遊戲',
         Personalization: '個人化',
         Other: '其他',
         IAP: 'App 內購買',
         'Paid Apps': '付費 App',
         'APAC': '亞太地區',
         'Canada': '加拿大',
         'Central and Eastern Europe': '中歐與東歐',
         'France': '法國',
         'Germany': '德國',
         'Greater China': '大中華區',
         'India': '印度',
         'Japan': '日本',
         'Latam': '拉丁美洲',
         'MEA': '中東與非洲',
         'UK': '英國',
         'United States': '美國',
         'Western Europe': '西歐',
         'World': '全球'
      }

   };

}
)();